In [28]:
from __future__ import absolute_import
import numpy as np
from mDAG_advanced import mDAG
from hypergraphs import LabelledHypergraph
from directed_structures import LabelledDirectedStructure
import itertools

In [13]:
IV_ds = LabelledDirectedStructure(variable_names=["X","A","B"],
                                  edge_list=[("X","A"), ("A","B")])
IV_sc = LabelledHypergraph(variable_names=["X","A","B"],
                           simplicial_complex=[("A","B")])
IV_mDAG = mDAG(directed_structure_instance=IV_ds,
               simplicial_complex_instance=IV_sc)

UC_ds = LabelledDirectedStructure(variable_names=["A","X","B"],
                                  edge_list=[("X","A"), ("X","B")])
UC_sc = LabelledHypergraph(variable_names=["A","X","B"],
                           simplicial_complex=[("X","A"),("X","B")])
UC_mDAG = mDAG(directed_structure_instance=UC_ds,
               simplicial_complex_instance=UC_sc)

In [14]:
print("d_sep: ", IV_mDAG.all_CI)
print("e_sep: ", IV_mDAG.all_esep)
print("Skeleton: ", IV_mDAG.skeleton_instance.as_string)

d_sep:  set()
e_sep:  {((0, 2), (), (1,))}
Skeleton:  [(0,1),(1,2)]


In [17]:
print("e_sep: ", UC_mDAG.all_esep)
print("Same e_sep: ", IV_mDAG.all_esep == UC_mDAG.all_esep)

e_sep:  {((0, 2), (), (1,))}
Same e_sep:  True


In [33]:

print("Infeasible supports: ", IV_mDAG.infeasible_binary_supports_n_events(2))
print("Infeasible supports beyond e_sep: ", IV_mDAG.smart_infeasible_binary_supports_n_events(2))
print("Infeasible supports beyond e_sep: ", IV_mDAG.no_infeasible_supports_beyond_esep_up_to(2))

IV_mDAG.smart_support_testing_instance(8).from_integer_to_matrix(
    list(itertools.chain.from_iterable(
        (IV_mDAG.infeasible_binary_supports_n_events(n) for n in range(2,7))
)))

Infeasible supports:  (5,)
Infeasible supports beyond e_sep:  ()
Infeasible supports beyond e_sep:  True


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 1],
        [1, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 1, 0],
        [1, 0, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 1, 1],
        [1, 0, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [1, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [1, 0, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],


In [40]:
print(IV_mDAG.smart_infeasible_binary_supports_n_events(3))

all((
    IV_mDAG.smart_infeasible_binary_supports_n_events(n)==
    IV_mDAG.smart_infeasible_binary_supports_n_events(n)
    for n in range(2,7)))


(21, 29)


True

In [43]:
#Example for Ilya
ILYA_ds = LabelledDirectedStructure(
    variable_names=["X", "A", "B", "C", "D"],
    edge_list=[("C","A"), ("C","B"), ("X","C"), ("D","A"), ("D","B")]
)

ILYA_sc1 = LabelledHypergraph(
    variable_names=["X", "A", "B", "C", "D"],
    simplicial_complex=[("A", "X", "D"), ("B", "X", "D"), ("A", "C")]
)
ILYA_sc2 = LabelledHypergraph(
    variable_names=["X", "A", "B", "C", "D"],
    simplicial_complex=[("A", "X", "D"), ("B", "X", "D")]
)
#Ilya's sc2 is weaker than sc1. Let's show that it matters.
ILYA_mDAG1=mDAG(directed_structure_instance=ILYA_ds,
                simplicial_complex_instance=ILYA_sc1)
ILYA_mDAG2=mDAG(directed_structure_instance=ILYA_ds,
                simplicial_complex_instance=ILYA_sc2)
strong_one_infeasible_supports=ILYA_mDAG1.smart_infeasible_binary_supports_n_events(4, verbose=True)
weak_one_infeasible_supports=ILYA_mDAG2.smart_infeasible_binary_supports_n_events(4, verbose=True)

supports_infeasible_only_in_weak = tuple(set(weak_one_infeasible_supports).difference(
    strong_one_infeasible_supports))
print("Number of infeasible in strong mDAG: ", len(strong_one_infeasible_supports))
print("Number of infeasible in weak mDAG: ", len(weak_one_infeasible_supports))
print("Number of examples that differ: ", len(supports_infeasible_only_in_weak))

print("An example of a support in one but not the other:")
print(ILYA_mDAG2.smart_support_testing_instance(4).from_integer_to_matrix(
    supports_infeasible_only_in_weak[0]
))

[nof_events=4] 1581 of 1581|################################| (Time:  0:00:03) 
[nof_events=4] 1581 of 1581|################################| (Time:  0:00:03) 


Number of infeasible in strong mDAG:  917
Number of infeasible in weak mDAG:  933
Number of examples that differ:  16
An example of a support in one but not the other:
[[0 0 0 0 0]
 [0 0 1 1 0]
 [1 0 0 0 0]
 [1 1 0 1 0]]


In [ ]:
#I suppose one might want to figure out all the mDAGs which are equivalent to a given mDAG.
# At the moment this is not implemented.