In [1]:
from __future__ import absolute_import
import numpy as np
from mDAG_advanced import mDAG
from hypergraphs import LabelledHypergraph
from directed_structures import LabelledDirectedStructure
import itertools

Visualization with matplotlib is disabled.


In [9]:
Reinforced_flag_ds=LabelledDirectedStructure(variable_names=["X","A","B","C"],
                                  edge_list=[("X","A"), ("X","B"), ("A","B")])
Reinforced_flag_sc=LabelledHypergraph(variable_names=["X","A","B","C"],
                                  simplicial_complex=[("A","C"), ("B","C")])
Hotair_balloon_sc=LabelledHypergraph(variable_names=["X","A","B","C"],
                                  simplicial_complex=[("A","B","C")])
Intermediate_sc=LabelledHypergraph(variable_names=["X","A","B","C"],
                                  simplicial_complex=[("A","C"), ("B","C"), ("A","B")])
Hotair_balloon_ds=LabelledDirectedStructure(variable_names=["X","A","B","C"],
                                  edge_list=[("X","A"), ("X","B"), ("A","B")])
Reinforced_flag_mDAG = mDAG(directed_structure_instance=Reinforced_flag_ds,
               simplicial_complex_instance=Reinforced_flag_sc)
Hotair_balloon_mDAG = mDAG(directed_structure_instance=Hotair_balloon_ds,
               simplicial_complex_instance=Hotair_balloon_sc)
Intermediate_mDAG = mDAG(directed_structure_instance=Hotair_balloon_ds,
               simplicial_complex_instance=Intermediate_sc)
print("Balloon:", Hotair_balloon_mDAG.infeasible_binary_supports_n_events_beyond_esep_as_matrices(4))
intermed_infeas = Intermediate_mDAG.infeasible_binary_supports_n_events_beyond_esep(6)
flag_infeas = Reinforced_flag_mDAG.infeasible_binary_supports_n_events_beyond_esep(6)
print(set(flag_infeas).difference(intermed_infeas))
# print("Intermediate:", intermed_infeas)
# print("Reinforced_flag:", intermed_infeas)

Balloon: []
{83855, 78991, 78989, 79004, 79006, 79021, 79023, 79036, 79038, 144781, 75149, 75151, 144783, 75181, 214415, 75164, 144796, 214430, 75166, 144798, 144813, 144815, 75183, 75196, 75198, 144828, 144830, 79501, 79503, 87695, 218767, 218780, 87693, 218765, 214925, 214927, 223117, 145293, 145295, 75661, 75663, 214942, 223132, 75676, 75678, 83868, 83870, 145310, 75693, 75695, 83885, 83887, 75708, 75710, 83900, 83902, 145308, 83853}


In [2]:
IV_ds = LabelledDirectedStructure(variable_names=["X","A","B"],
                                  edge_list=[("X","A"), ("A","B")])
IV_sc = LabelledHypergraph(variable_names=["X","A","B"],
                           simplicial_complex=[("A","B")])
IV_mDAG = mDAG(directed_structure_instance=IV_ds,
               simplicial_complex_instance=IV_sc)

UC_ds = LabelledDirectedStructure(variable_names=["X","A","B"],
                                  edge_list=[("A","X"), ("A","B")])
UC_sc = LabelledHypergraph(variable_names=["X","A","B"],
                           simplicial_complex=[("A","X"),("A","B")])
UC_mDAG = mDAG(directed_structure_instance=UC_ds,
               simplicial_complex_instance=UC_sc)

print(IV_mDAG)

{X:[A],A:[B],B:[]}|[(A,B)]


In [3]:
print("IV d_sep: ", IV_mDAG.all_CI)
print("IV e_sep: ", IV_mDAG.all_esep)
print("IV Skeleton: ", IV_mDAG.skeleton)
print("IV Skeleton: ", IV_mDAG.skeleton_instance.as_string)
print("IV Densely connected pairs: ", IV_mDAG.all_densely_connected_pairs)

IV d_sep:  set()
IV e_sep:  {(('B', 'X'), (), ('A',))}
IV Skeleton:  14
IV Skeleton:  [(A,B),(A,X)]
IV Densely connected pairs:  {('A', 'X'), ('A', 'B'), ('B', 'X')}


In [4]:
print("UC e_sep: ", UC_mDAG.all_esep)
print("UC Densely connected pairs: ", UC_mDAG.all_densely_connected_pairs)
print("Same e_sep: ", IV_mDAG.all_esep == UC_mDAG.all_esep)

UC e_sep:  {(('B', 'X'), (), ('A',))}
UC Densely connected pairs:  {('A', 'X'), ('A', 'B'), ('B', 'X')}
Same e_sep:  True


In [5]:

print("IV infeasible supports over 2 events: ", IV_mDAG.infeasible_binary_supports_n_events_as_matrices(2))
print("IV infeasible supports beyond e_sep over 2 events: ", IV_mDAG.infeasible_binary_supports_n_events_beyond_esep_as_matrices(2))
print("No infeasible supports beyond e_sep over 2 events: ", IV_mDAG.no_infeasible_binary_supports_beyond_esep(2))

print("UC infeasible supports beyond e-sep: ", UC_mDAG.infeasible_binary_supports_beyond_esep_as_matrices_up_to(7))
print("IV infeasible supports beyond e-sep: ")
for mat in IV_mDAG.infeasible_binary_supports_beyond_esep_as_matrices_up_to(7):
    print(mat)


IV infeasible supports over 2 events:  [[[0 0 0]
  [1 0 1]]]
IV infeasible supports beyond e_sep over 2 events:  []
No infeasible supports beyond e_sep over 2 events:  True
UC infeasible supports beyond e-sep:  []
IV infeasible supports beyond e-sep: 
[[0 0 0]
 [0 1 0]
 [1 0 1]]
[[0 0 0]
 [0 1 1]
 [1 0 1]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 1]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 1 1]]
[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 0]]
[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 1]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]]


In [6]:
print(IV_mDAG.infeasible_binary_supports_n_events_beyond_esep_as_matrices(3))
print(UC_mDAG.infeasible_binary_supports_n_events_beyond_esep_as_matrices(3))


[[[0 0 0]
  [0 1 0]
  [1 0 1]]

 [[0 0 0]
  [0 1 1]
  [1 0 1]]]
[]


In [7]:
#Example for Ilya
ILYA_ds = LabelledDirectedStructure(
    variable_names=["X", "A", "B", "C", "D"],
    edge_list=[("C","A"), ("C","B"), ("X","C"), ("D","A"), ("D","B")]
)

ILYA_sc1 = LabelledHypergraph(
    variable_names=["X", "A", "B", "C", "D"],
    simplicial_complex=[("A", "X", "D"), ("B", "X", "D"), ("A", "C")]
)
ILYA_sc2 = LabelledHypergraph(
    variable_names=["X", "A", "B", "C", "D"],
    simplicial_complex=[("A", "X", "D"), ("B", "X", "D")]
)

#Ilya's sc2 is weaker than sc1. Let's show that it matters.
ILYA_mDAG1=mDAG(directed_structure_instance=ILYA_ds,
                simplicial_complex_instance=ILYA_sc1)
ILYA_mDAG2=mDAG(directed_structure_instance=ILYA_ds,
                simplicial_complex_instance=ILYA_sc2)

print("Same e_sep? ", ILYA_mDAG1.all_esep == ILYA_mDAG2.all_esep)

strong_one_infeasible_supports=ILYA_mDAG1.infeasible_binary_supports_n_events_beyond_esep(4, verbose=True)
weak_one_infeasible_supports=ILYA_mDAG2.infeasible_binary_supports_n_events_beyond_esep(4, verbose=True)

supports_infeasible_only_in_weak = tuple(set(weak_one_infeasible_supports).difference(
    strong_one_infeasible_supports))
print("Number of infeasible in strong mDAG: ", len(strong_one_infeasible_supports))
print("Number of infeasible in weak mDAG: ", len(weak_one_infeasible_supports))
print("Number of examples that differ: ", len(supports_infeasible_only_in_weak))

print("An example of a support in one but not the other:")
print(ILYA_mDAG2.support_testing_instance_binary(4).from_integer_to_matrix(
    supports_infeasible_only_in_weak[0]
))

Same e_sep?  True


[nof_events=4] 1581 of 1581|################################| (Time:  0:00:03) 
[nof_events=4] 1581 of 1581|################################| (Time:  0:00:03) 


Number of infeasible in strong mDAG:  917
Number of infeasible in weak mDAG:  933
Number of examples that differ:  16
An example of a support in one but not the other:
[[0 0 0 0 0]
 [0 0 1 1 0]
 [1 0 0 0 0]
 [1 1 0 1 0]]


In [8]:
#I suppose one might want to figure out all the mDAGs which are equivalent to a given mDAG.
# At the moment this is not implemented.
print(ILYA_mDAG1.all_densely_connected_pairs)
print(ILYA_mDAG2.all_densely_connected_pairs)

{('A', 'X'), ('B', 'C'), ('C', 'X'), ('A', 'C'), ('A', 'D'), ('D', 'X'), ('B', 'D'), ('A', 'B'), ('B', 'X')}
{('A', 'X'), ('B', 'C'), ('C', 'X'), ('A', 'C'), ('A', 'D'), ('D', 'X'), ('B', 'D'), ('A', 'B'), ('B', 'X')}


In [9]:
len(ILYA_mDAG2.all_densely_connected_pairs)

9

In [14]:
for n in range(2,5):
    print("Testing ",n," event supports:")
    print("No infeasible beyond esep?: ",
          UC_mDAG.support_testing_instance((4,4,4),n).no_infeasible_supports_beyond_esep(verbose=True))

Testing  2  event supports:
No infeasible beyond esep?:  True
Testing  3  event supports:
No infeasible beyond esep?:  True
Testing  4  event supports:
No infeasible beyond esep?:  True
